/* GENERATED by evals/gen-component-index.js — do not edit by hand.
   Source of truth: prototypes/navigation/main.css
   Regenerate:  node evals/gen-component-index.js
   Verify:      node evals/gen-component-index.js --check

   77 blocks. Consumed by system/components/index.html. */
window.MHT_COMPONENTS = [
  {
    "block": "panel",
    "tier": "chrome",
    "rules": 29,
    "parts": [
      "brand",
      "explore",
      "footer",
      "hub",
      "hub-icon",
      "hubs",
      "logotype",
      "promo",
      "promo-cta",
      "promo-graphic",
      "promo-link",
      "promo-sub",
      "promo-title",
      "tab",
      "tab-icon",
      "tabs",
      "top",
      "topics",
      "topics-label"
    ],
    "variants": [
      "bl",
      "tr"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "footer",
    "tier": "chrome",
    "rules": 24,
    "parts": [
      "bar",
      "brand",
      "col",
      "copyright",
      "disclaimer",
      "dot",
      "end",
      "headline",
      "legal",
      "link",
      "links",
      "logo",
      "privacy"
    ],
    "variants": [
      "dark"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "art",
    "tier": "surface",
    "rules": 21,
    "parts": [
      "avatar",
      "body",
      "byline",
      "end",
      "h2",
      "head",
      "ic",
      "lede",
      "reaction",
      "save",
      "sec",
      "strip",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-hero",
    "tier": "module",
    "rules": 19,
    "parts": [
      "avatar",
      "avatars",
      "count",
      "cta",
      "intro",
      "ring",
      "sub",
      "title",
      "users"
    ],
    "variants": [
      "br",
      "tl"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "feat-card",
    "tier": "surface",
    "rules": 17,
    "parts": [
      "cat",
      "desc",
      "head",
      "illo",
      "panel",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "screen",
    "tier": "chrome",
    "rules": 16,
    "parts": [
      "body",
      "nav",
      "placeholder",
      "scroll",
      "subnav",
      "uplevel"
    ],
    "variants": [
      "fill",
      "flow"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-preview",
    "tier": "surface",
    "rules": 16,
    "parts": [
      "avatar",
      "avatars",
      "banner",
      "banner-graphic",
      "banner-inner",
      "count",
      "head",
      "list",
      "status",
      "sub",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-feed",
    "tier": "surface",
    "rules": 16,
    "parts": [
      "arrows",
      "body",
      "cards",
      "header",
      "link",
      "post-btn",
      "scroll",
      "section",
      "title"
    ],
    "variants": [
      "gated"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "gate",
    "tier": "chrome",
    "rules": 15,
    "parts": [
      "close",
      "footer",
      "headline",
      "login",
      "option",
      "option-icon",
      "option-label",
      "options",
      "sub",
      "text"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "dnav",
    "tier": "chrome",
    "rules": 15,
    "parts": [
      "bar",
      "cluster",
      "crumb",
      "crumbbar",
      "link",
      "logo",
      "nav",
      "right"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "feat-pair-card",
    "tier": "surface",
    "rules": 14,
    "parts": [
      "head",
      "illo",
      "link",
      "panel",
      "preview"
    ],
    "variants": [
      "tight"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-advisors",
    "tier": "module",
    "rules": 13,
    "parts": [
      "body",
      "intro",
      "lede",
      "list",
      "title",
      "watch",
      "watch-card",
      "watch-head",
      "watch-title"
    ],
    "variants": [
      "italic"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "assistant-nudge",
    "tier": "surface",
    "rules": 13,
    "parts": [
      "caret",
      "close",
      "cta",
      "text"
    ],
    "variants": [
      "tappable"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "feat-pair",
    "tier": "surface",
    "rules": 13,
    "parts": [
      "avatar",
      "check",
      "person",
      "person-name",
      "person-role",
      "person-text",
      "rule"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-reminder",
    "tier": "surface",
    "rules": 13,
    "parts": [
      "cta",
      "graphic",
      "sub",
      "text",
      "title"
    ],
    "variants": [
      "bl",
      "tr"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "dropdown",
    "tier": "chrome",
    "rules": 13,
    "parts": [
      "divider",
      "item",
      "menu",
      "user"
    ],
    "variants": [
      "logout",
      "notif"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "topic-hub-mod",
    "tier": "surface",
    "rules": 12,
    "parts": [
      "desc",
      "head",
      "note",
      "preview",
      "soon",
      "title"
    ],
    "variants": [
      "disabled"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-cta-card",
    "tier": "module",
    "rules": 11,
    "parts": [
      "buttons",
      "graphic",
      "sub",
      "text",
      "title"
    ],
    "variants": [
      "bl",
      "tr"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-group",
    "tier": "surface",
    "rules": 11,
    "parts": [
      "check",
      "content",
      "desc",
      "icon",
      "left",
      "meta",
      "name",
      "text"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "art-keep",
    "tier": "surface",
    "rules": 11,
    "parts": [
      "card",
      "h",
      "scroll",
      "thumb",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "advisor-card",
    "tier": "surface",
    "rules": 10,
    "parts": [
      "bio",
      "identity",
      "link",
      "name",
      "org",
      "photo",
      "role",
      "text"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-person",
    "tier": "surface",
    "rules": 10,
    "parts": [
      "add",
      "avatar",
      "left",
      "meta",
      "name",
      "text"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "topic-hub",
    "tier": "surface",
    "rules": 10,
    "parts": [
      "desc",
      "header",
      "list",
      "name",
      "stat"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "art-answered",
    "tier": "surface",
    "rules": 10,
    "parts": [
      "ask",
      "label",
      "q",
      "stars",
      "tags",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "ai-btn",
    "tier": "primitive",
    "rules": 9,
    "parts": [
      "label",
      "stars"
    ],
    "variants": [],
    "inJs": true,
    "contract": "ai-btn.md"
  },
  {
    "block": "mod-factoid",
    "tier": "module",
    "rules": 8,
    "parts": [
      "source",
      "stats",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-checker-card",
    "tier": "module",
    "rules": 8,
    "parts": [
      "action",
      "cta",
      "note",
      "pills",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-article-card",
    "tier": "module",
    "rules": 8,
    "parts": [
      "stack",
      "thumb",
      "title",
      "title-text"
    ],
    "variants": [
      "collection"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "nav",
    "tier": "chrome",
    "rules": 8,
    "parts": [
      "left",
      "right",
      "top"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-listicle-card",
    "tier": "module",
    "rules": 7,
    "parts": [
      "cta",
      "icon",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-post",
    "tier": "surface",
    "rules": 7,
    "parts": [
      "avatar",
      "body",
      "eyebrow",
      "text"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-q",
    "tier": "surface",
    "rules": 7,
    "parts": [
      "answers",
      "by",
      "text",
      "user"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "uplevel",
    "tier": "primitive",
    "rules": 6,
    "parts": [
      "icon"
    ],
    "variants": [],
    "inJs": true,
    "contract": "uplevel.md"
  },
  {
    "block": "mod-listicles",
    "tier": "module",
    "rules": 6,
    "parts": [
      "scroll"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-articles",
    "tier": "module",
    "rules": 6,
    "parts": [
      "scroll"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-mod",
    "tier": "surface",
    "rules": 6,
    "parts": [
      "badge",
      "desc",
      "head",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "art-note",
    "tier": "surface",
    "rules": 6,
    "parts": [
      "bullet",
      "item",
      "link",
      "text",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-btn-primary",
    "tier": "primitive",
    "rules": 5,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": "mod-btn-primary.md"
  },
  {
    "block": "mod-btn-secondary",
    "tier": "primitive",
    "rules": 5,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": "mod-btn-secondary.md"
  },
  {
    "block": "launcher-hotspot",
    "tier": "chrome",
    "rules": 5,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-experts",
    "tier": "module",
    "rules": 5,
    "parts": [
      "list"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-article",
    "tier": "module",
    "rules": 5,
    "parts": [
      "eyebrow",
      "meta",
      "title"
    ],
    "variants": [],
    "inJs": false,
    "contract": null
  },
  {
    "block": "mod-section-text",
    "tier": "module",
    "rules": 5,
    "parts": [
      "sub",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-expert-card",
    "tier": "module",
    "rules": 5,
    "parts": [
      "avatar",
      "info",
      "name",
      "role"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-stat-card",
    "tier": "module",
    "rules": 5,
    "parts": [
      "graphic",
      "number",
      "text"
    ],
    "variants": [
      "wide"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-ic",
    "tier": "surface",
    "rules": 5,
    "parts": [
      "action",
      "bg",
      "glyph",
      "ink",
      "ink-stroke"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "comm-hub",
    "tier": "surface",
    "rules": 5,
    "parts": [
      "list",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "art-conv",
    "tier": "surface",
    "rules": 5,
    "parts": [
      "input",
      "title"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-carousel-arrow",
    "tier": "primitive",
    "rules": 5,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "join-btn",
    "tier": "primitive",
    "rules": 4,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "subnav",
    "tier": "chrome",
    "rules": 4,
    "parts": [
      "link"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "collection-callout",
    "tier": "surface",
    "rules": 4,
    "parts": [
      "label",
      "link",
      "text"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "feat",
    "tier": "surface",
    "rules": 4,
    "parts": [
      "heading",
      "list"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "art-collapse",
    "tier": "surface",
    "rules": 4,
    "parts": [
      "link"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "icon-btn",
    "tier": "primitive",
    "rules": 3,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": "icon-btn.md"
  },
  {
    "block": "profile-btn",
    "tier": "primitive",
    "rules": 3,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "phone",
    "tier": "chrome",
    "rules": 3,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-community",
    "tier": "module",
    "rules": 3,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-quote-card",
    "tier": "module",
    "rules": 3,
    "parts": [
      "text"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "logo",
    "tier": "primitive",
    "rules": 3,
    "parts": [],
    "variants": [
      "full",
      "mark"
    ],
    "inJs": true,
    "contract": null
  },
  {
    "block": "panel-overlay",
    "tier": "chrome",
    "rules": 3,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-pill",
    "tier": "primitive",
    "rules": 2,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "flow-close",
    "tier": "chrome",
    "rules": 2,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-carousel-arrows",
    "tier": "primitive",
    "rules": 2,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-quotes",
    "tier": "module",
    "rules": 2,
    "parts": [
      "scroll"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-disclaimer-note",
    "tier": "module",
    "rules": 2,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "icon",
    "tier": "primitive",
    "rules": 2,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "ai-grad",
    "tier": "surface",
    "rules": 2,
    "parts": [
      "from",
      "to"
    ],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "profile-avatar",
    "tier": "primitive",
    "rules": 2,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "stage",
    "tier": "chrome",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "mod-view-all-link",
    "tier": "primitive",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "logo-btn",
    "tier": "primitive",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "logo-accent",
    "tier": "primitive",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "logo-ink",
    "tier": "primitive",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "gate-overlay",
    "tier": "chrome",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "dropdown-overlay",
    "tier": "chrome",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  },
  {
    "block": "art-access",
    "tier": "surface",
    "rules": 1,
    "parts": [],
    "variants": [],
    "inJs": true,
    "contract": null
  }
];
