/* Editorial icon categories and display names.
   AUTHORED, not generated — the grouping is a human judgment about what each
   icon is for. evals/gen-icon-registry.js --check verifies that every file
   appears in exactly one category, so a new icon cannot go uncategorised.

   Loaded by system/icons/sheet.html. */
window.MHT_ICON_CATEGORIES = {
  "Body & symptoms": [
    "sweating",
    "fan",
    "airflow",
    "shower",
    "sleep",
    "bedding",
    "mood",
    "confusion",
    "head-spiral",
    "headache",
    "fatigue",
    "joint-pain",
    "pain",
    "dry-eyes",
    "weight",
    "muscle",
    "menopause"
  ],
  "Anatomy": [
    "brain",
    "brain-activity",
    "heart-anatomy",
    "heart-health",
    "heart-risk",
    "heart-declining",
    "circulation",
    "blood",
    "blood-sugar",
    "lungs",
    "liver",
    "digestive",
    "spine",
    "bone",
    "back",
    "genetics",
    "hormones",
    "cells",
    "breast-health",
    "ostomy",
    "fertility",
    "pregnancy"
  ],
  "Care": [
    "appointment",
    "clinic",
    "doctor",
    "assessment",
    "checklist",
    "screening",
    "diagnosis",
    "detection",
    "health-check",
    "vaccination",
    "injection",
    "iv-drip",
    "medication",
    "pill-bottle",
    "treatment",
    "surgery",
    "records",
    "personalised-care",
    "hygiene",
    "clock",
    "time",
    "cost",
    "changes",
    "awareness"
  ],
  "Support & messaging": [
    "community",
    "group",
    "peer-support",
    "sitting-together",
    "family",
    "family-group",
    "network",
    "talk",
    "comment",
    "messages",
    "support",
    "medical-chat",
    "chat-check",
    "notification",
    "question",
    "ask-a-question",
    "language",
    "open-hands",
    "comfort",
    "partnership",
    "inclusion",
    "inclusive",
    "avatar",
    "quote"
  ],
  "Living": [
    "wellbeing",
    "heart",
    "heart-care",
    "heart-message",
    "broken-heart",
    "nutrition",
    "water",
    "exercise",
    "running-shoe",
    "morning",
    "home",
    "mood-tracking",
    "journey",
    "cosmetics",
    "mirror",
    "laptop",
    "meeting",
    "menu",
    "sparkle",
    "achievement",
    "recognition",
    "empowerment",
    "privacy",
    "confidential",
    "protection"
  ]
};

window.MHT_ICON_NAMES = {
  "sweating": "Sweating",
  "fan": "Fan",
  "airflow": "Airflow",
  "shower": "Shower",
  "sleep": "Sleep",
  "bedding": "Bedding",
  "mood": "Mood changes",
  "confusion": "Confusion",
  "head-spiral": "Head spiral",
  "headache": "Headache",
  "fatigue": "Fatigue",
  "joint-pain": "Joint pain",
  "pain": "Pain",
  "dry-eyes": "Dry eyes",
  "weight": "Weight",
  "muscle": "Muscle",
  "menopause": "Menopause",
  "brain": "Brain",
  "brain-activity": "Brain activity",
  "heart-anatomy": "Heart anatomy",
  "heart-health": "Heart health",
  "heart-risk": "Heart risk",
  "heart-declining": "Heart declining",
  "circulation": "Circulation",
  "blood": "Blood",
  "blood-sugar": "Blood sugar",
  "lungs": "Lungs",
  "liver": "Liver",
  "digestive": "Digestive",
  "spine": "Spine",
  "bone": "Bone",
  "back": "Back",
  "genetics": "Genetics",
  "hormones": "Hormones",
  "cells": "Cells",
  "breast-health": "Breast health",
  "ostomy": "Ostomy",
  "fertility": "Fertility",
  "pregnancy": "Pregnancy",
  "appointment": "Appointment",
  "clinic": "Clinic",
  "doctor": "Doctor",
  "assessment": "Assessment",
  "checklist": "Checklist",
  "screening": "Screening",
  "diagnosis": "Diagnosis",
  "detection": "Detection",
  "health-check": "Health check",
  "vaccination": "Vaccination",
  "injection": "Injection",
  "iv-drip": "IV drip",
  "medication": "Medication",
  "pill-bottle": "Pill bottle",
  "treatment": "Treatment",
  "surgery": "Surgery",
  "records": "Records",
  "personalised-care": "Personalised care",
  "hygiene": "Hygiene",
  "clock": "Clock",
  "time": "Time",
  "cost": "Cost",
  "changes": "Changes",
  "awareness": "Awareness",
  "community": "Community",
  "group": "Group",
  "peer-support": "Peer support",
  "sitting-together": "Sitting together",
  "family": "Family",
  "family-group": "Family group",
  "network": "Network",
  "talk": "Talk",
  "comment": "Comment",
  "messages": "Messages",
  "support": "Support",
  "medical-chat": "Medical chat",
  "chat-check": "Chat check",
  "notification": "Notification",
  "question": "Question",
  "ask-a-question": "Ask a question",
  "language": "Language",
  "open-hands": "Open hands",
  "comfort": "Comfort",
  "partnership": "Partnership",
  "inclusion": "Inclusion",
  "inclusive": "Inclusive",
  "avatar": "Avatar",
  "quote": "Quote",
  "wellbeing": "Wellbeing",
  "heart": "Heart",
  "heart-care": "Heart care",
  "heart-message": "Heart message",
  "broken-heart": "Broken heart",
  "nutrition": "Nutrition",
  "water": "Water",
  "exercise": "Exercise",
  "running-shoe": "Running shoe",
  "morning": "Morning",
  "home": "Home",
  "mood-tracking": "Mood tracking",
  "journey": "Journey",
  "cosmetics": "Cosmetics",
  "mirror": "Mirror",
  "laptop": "Laptop",
  "meeting": "Meeting",
  "menu": "Menu",
  "sparkle": "Sparkle",
  "achievement": "Achievement",
  "recognition": "Recognition",
  "empowerment": "Empowerment",
  "privacy": "Privacy",
  "confidential": "Confidential",
  "protection": "Protection"
};

window.MHT_ICON_CATEGORY_NOTES = {
  "Body & symptoms": "Conditions, sensations and states the body is in.",
  "Anatomy": "Systems, organs and biology.",
  "Care": "Appointments, treatment, testing and records.",
  "Support & messaging": "People, conversation and notifications.",
  "Living": "Wellbeing, habits, recognition and trust."
};
