/* GENERATED by evals/gen-token-manifest.js — do not edit by hand.
   Source of truth: system/tokens/tokens.css
   Regenerate:  node evals/gen-token-manifest.js
   Verify:      node evals/gen-token-manifest.js --check

   54 tokens. The declared value is here for reference; the page
   resolves the LIVE value with getComputedStyle, so a themed --brand-* shows
   what the browser actually computes. */
window.MHT_TOKENS = [
  {
    "name": "--color-primary",
    "value": "#0f57a8",
    "group": "Action",
    "note": "primary action — buttons, links"
  },
  {
    "name": "--color-primary-soft",
    "value": "#dee5f1",
    "group": "Action",
    "note": "soft primary tint — hover/rollover"
  },
  {
    "name": "--color-navy",
    "value": "#2b2b68",
    "group": "Action",
    "note": "dark gradient anchor, display headlines"
  },
  {
    "name": "--color-text",
    "value": "#0d1b29",
    "group": "Ink",
    "note": "primary ink"
  },
  {
    "name": "--color-text-secondary",
    "value": "#626b74",
    "group": "Ink",
    "note": "secondary / label text"
  },
  {
    "name": "--color-text-muted",
    "value": "rgba(13, 27, 41, 0.7)",
    "group": "Ink",
    "note": ""
  },
  {
    "name": "--color-text-inverse",
    "value": "#ffffff",
    "group": "Ink",
    "note": "ink on dark or accent surfaces"
  },
  {
    "name": "--color-surface",
    "value": "#ffffff",
    "group": "Surfaces",
    "note": "default card / panel surface"
  },
  {
    "name": "--color-surface-muted",
    "value": "#eef0f3",
    "group": "Surfaces",
    "note": "muted neutral surface"
  },
  {
    "name": "--color-surface-neutral",
    "value": "#f6f7f9",
    "group": "Surfaces",
    "note": "neutral section surface"
  },
  {
    "name": "--color-surface-sunken",
    "value": "#f3f4f6",
    "group": "Surfaces",
    "note": "recessed surface — footer end, wells"
  },
  {
    "name": "--color-bg-warm",
    "value": "#fbf7f3",
    "group": "Surfaces",
    "note": "warm banner background"
  },
  {
    "name": "--color-bg-cool",
    "value": "#fafcff",
    "group": "Surfaces",
    "note": "cool neutral section background"
  },
  {
    "name": "--color-bg-blue-soft",
    "value": "#edf3f9",
    "group": "Surfaces",
    "note": "soft blue section background — Experts (Figma 4122:332)"
  },
  {
    "name": "--color-border",
    "value": "#dbdddf",
    "group": "Lines",
    "note": "standard hairline"
  },
  {
    "name": "--color-divider",
    "value": "#e5e5e5",
    "group": "Lines",
    "note": "lighter rule between list rows"
  },
  {
    "name": "--color-card-border",
    "value": "rgba(13, 27, 41, 0.15)",
    "group": "Lines",
    "note": ""
  },
  {
    "name": "--color-pill-border",
    "value": "rgba(13, 27, 41, 0.44)",
    "group": "Lines",
    "note": ""
  },
  {
    "name": "--color-border-primary-soft",
    "value": "#d6e2f1",
    "group": "Lines",
    "note": "soft primary-tinted border"
  },
  {
    "name": "--color-placeholder",
    "value": "#e9ebee",
    "group": "Media placeholders",
    "note": ""
  },
  {
    "name": "--color-placeholder-alt",
    "value": "var(--color-surface-sunken)",
    "group": "Media placeholders",
    "note": ""
  },
  {
    "name": "--color-placeholder-cool",
    "value": "#eef1f7",
    "group": "Media placeholders",
    "note": ""
  },
  {
    "name": "--color-placeholder-shade",
    "value": "#e3e6ea",
    "group": "Media placeholders",
    "note": ""
  },
  {
    "name": "--color-placeholder-photo",
    "value": "#c6c0c8",
    "group": "Media placeholders",
    "note": "warm gray standing in for a portrait/photo"
  },
  {
    "name": "--color-badge",
    "value": "#ff741d",
    "group": "Status",
    "note": "notification badge / chip — orange"
  },
  {
    "name": "--color-badge-soft",
    "value": "rgba(255, 116, 29, 0.05)",
    "group": "Status",
    "note": ""
  },
  {
    "name": "--color-accent",
    "value": "var(--brand-accent)",
    "group": "Brand accent (resolved by the theme file)",
    "note": ""
  },
  {
    "name": "--color-accent-soft",
    "value": "var(--brand-accent-soft)",
    "group": "Brand accent (resolved by the theme file)",
    "note": ""
  },
  {
    "name": "--color-accent-soft-solid",
    "value": "var(--brand-accent-soft-solid)",
    "group": "Brand accent (resolved by the theme file)",
    "note": ""
  },
  {
    "name": "--color-accent-strong",
    "value": "var(--brand-accent-strong)",
    "group": "Brand accent (resolved by the theme file)",
    "note": ""
  },
  {
    "name": "--color-accent-light",
    "value": "var(--brand-accent-light)",
    "group": "Brand accent (resolved by the theme file)",
    "note": ""
  },
  {
    "name": "--color-accent-pale",
    "value": "var(--brand-accent-pale)",
    "group": "Brand accent (resolved by the theme file)",
    "note": "AA-safe accent on dark scrims — the full accent sits at ~2.4:1 there and fails"
  },
  {
    "name": "--color-bg-accent-soft",
    "value": "var(--brand-bg-accent-soft)",
    "group": "Brand accent (resolved by the theme file)",
    "note": ""
  },
  {
    "name": "--color-scrim",
    "value": "var(--brand-scrim)",
    "group": "Brand accent (resolved by the theme file)",
    "note": "dark backdrop behind a COLOR-blended photo"
  },
  {
    "name": "--radius-pill",
    "value": "999px",
    "group": "Radius",
    "note": ""
  },
  {
    "name": "--radius-card",
    "value": "16px",
    "group": "Radius",
    "note": ""
  },
  {
    "name": "--font-body",
    "value": "\"Lato\", sans-serif",
    "group": "Type families",
    "note": ""
  },
  {
    "name": "--font-display",
    "value": "\"DM Serif Display\", serif",
    "group": "Type families",
    "note": ""
  },
  {
    "name": "--display-hero-size",
    "value": "40px",
    "group": "Display type scale (DM Serif Display)",
    "note": ""
  },
  {
    "name": "--display-hero-lh",
    "value": "48px",
    "group": "Display type scale (DM Serif Display)",
    "note": ""
  },
  {
    "name": "--display-section-size",
    "value": "32px",
    "group": "Display type scale (DM Serif Display)",
    "note": ""
  },
  {
    "name": "--display-section-lh",
    "value": "40px",
    "group": "Display type scale (DM Serif Display)",
    "note": ""
  },
  {
    "name": "--display-title-size",
    "value": "28px",
    "group": "Display type scale (DM Serif Display)",
    "note": ""
  },
  {
    "name": "--display-title-lh",
    "value": "36px",
    "group": "Display type scale (DM Serif Display)",
    "note": ""
  },
  {
    "name": "--display-subhead-size",
    "value": "24px",
    "group": "Display type scale (DM Serif Display)",
    "note": "DM Serif Display sub-heading tier. Figma-confirmed (Entry-Points file, nodes 49:1845/49:1855/49:1890)."
  },
  {
    "name": "--display-subhead-lh",
    "value": "32px",
    "group": "Display type scale (DM Serif Display)",
    "note": "size+8, same rule as every other tier"
  },
  {
    "name": "--display-tracking",
    "value": "-0.75px",
    "group": "Display type scale (DM Serif Display)",
    "note": ""
  },
  {
    "name": "--quote-size",
    "value": "24px",
    "group": "Display type scale (DM Serif Display)",
    "note": "Lato SemiBold quote text only — unrelated to --display-subhead-size"
  },
  {
    "name": "--quote-lh",
    "value": "30px",
    "group": "Display type scale (DM Serif Display)",
    "note": "matches the Figma Lato \"Headline\" 24px swatch (node 40:260)"
  },
  {
    "name": "--content-max",
    "value": "1000px",
    "group": "Responsive layout",
    "note": "the single desktop content width — nav + all sections align to this"
  },
  {
    "name": "--content-column",
    "value": "728px",
    "group": "Responsive layout",
    "note": "reading column — articles and other content pages"
  },
  {
    "name": "--content-gutter",
    "value": "clamp(16px, 5vw, 40px)",
    "group": "Responsive layout",
    "note": "minimum side gutter before the 1000px box centers"
  },
  {
    "name": "--content-pad",
    "value": "max(var(--content-gutter), calc((100% - var(--content-max)) / 2))",
    "group": "Responsive layout",
    "note": ""
  },
  {
    "name": "--mobile-max",
    "value": "480px",
    "group": "Responsive layout",
    "note": "mobile layout column cap below the desktop breakpoint"
  }
];
window.MHT_TOKENS_RESPONSIVE = ["--color-text","--color-text-secondary","--color-text-muted","--color-text-inverse","--color-surface","--color-surface-neutral","--color-surface-muted","--color-surface-sunken","--color-bg-warm","--color-bg-cool","--color-bg-blue-soft","--color-border","--color-divider","--color-card-border","--color-pill-border","--color-border-primary-soft","--color-primary","--color-primary-soft","--color-placeholder","--color-placeholder-alt","--color-placeholder-cool","--color-placeholder-shade","--color-placeholder-photo","--color-accent","--color-accent-soft","--color-accent-soft-solid","--color-bg-accent-soft","--display-hero-size","--display-hero-lh","--display-section-size","--display-section-lh","--display-title-size","--display-title-lh","--display-subhead-size","--display-subhead-lh"];
